### PR TITLE
Implement Riak TimeSeries support for PB

### PR DESCRIPTION
**Pull request by christophermancini**

### CODE REVIEW

**Comment by ChristianRiesen** [comment]
Can we have TS support in both this and the riak client finalized? Tried to run with it using the branches but then it fails miserably here:
basho/riak-pb dev-ts requires allegro/protobuf dev-master -> no matching package found.

**Comment by christophermancini** [comment]
Yep, I have been working on it the last day or so. Should have it cleaned up and released today.

**Comment by ChristianRiesen** [comment]
Great news, thanks for the update. Saw the post about Riak TS and dove into it, banging my head against a couple roadblocks like this. Anything I could help you with?

**Comment by christophermancini** [comment]
Ok, this is ready for testing.

Time series tests can be run via phpunit:

`./vendor/bin/phpunit TimeSeriesOperationsTest vendor/basho/riak/tests/functional/TimeSeriesOperationsTest.php`

@ChristianRiesen I am thinking your issue with composer is a min stability issue, since this is a dev branch. Try add min stability flag to your composer.json and running composer update again, like this:

```
{
  "minimum-stability": "dev",
  "require": {
    "basho/riak-pb": "dev-ts"
  }
}
```

**Comment by lukebakken** [comment]
@christophermancini - I built 5.6 from source and get this when trying to run the tests:

```
lbakken@brahms ~/Projects/basho/riak-phppb-client (ts=)
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing nette/utils (v2.2.8)
  - Installing nette/utils (v2.3.8)
    Loading from cache

  - Removing nette/neon (v2.2.0)
  - Installing nette/neon (v2.3.4)
    Downloading: 100%

  - Removing nette/di (v2.2.6)
  - Installing nette/di (v2.3.10)
    Downloading: 100%

  - Removing kdyby/events (v2.3.2)
  - Installing kdyby/events (v2.4.1)
    Downloading: 100%

  - Removing nette/bootstrap (v2.2.6)
  - Installing nette/bootstrap (v2.3.4)
    Downloading: 100%

  - Removing nette/mail (v2.2.0)
  - Installing nette/mail (v2.3.5)
    Downloading: 100%

  - Removing nette/component-model (v2.2.3)
  - Installing nette/component-model (v2.2.4)
    Loading from cache

Writing lock file
Generating autoload files

lbakken@brahms ~/Projects/basho/riak-phppb-client (ts=)
$ ./vendor/bin/phpunit TimeSeriesOperationsTest vendor/basho/riak/tests/functional/TimeSeriesOperationsTest.php
PHPUnit 4.5.1 by Sebastian Bergmann and contributors.

Configuration read from /home/lbakken/Projects/basho/riak-phppb-client/phpunit.xml

This is a stub file for IDEs, don't use it directly!

lbakken@brahms ~/Projects/basho/riak-phppb-client (ts=)
$ php --version
PHP 5.6.21 (cli) (built: May 12 2016 17:13:00)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

lbakken@brahms ~/Projects/basho/riak-phppb-client (ts=)
$ fgrep -r 'This is a stub file for IDEs, don'\''t use it directly' *
vendor/allegro/protobuf/stubs/ProtobufMessage.php:die("This is a stub file for IDEs, don't use it directly!");
```

**Comment by christophermancini** [comment]
@lukebakken you have to build and install the extension for PB as well. Thats why I have them separate is this extra dependency. Full instructions are in the readme.

```
cd vendor/allegro/protobuf
phpize
./configure
make
make install
```

**Comment by lukebakken** [comment]
Got it, I'm surprised that doesn't happen automatically. Any way to put all this stuff into a Makefile?

**Comment by christophermancini** [comment]
Its part of the downside of PB on PHP. The most common way extensions are installed for PHP is via package manager. We could explore that as an option going forward, e.g. `sudo yum install -y php-pb`. Extensions are C modules that are referenced at runtime time and not part of the source code dependencies.

**Comment by lukebakken** [comment]
FYI, I had to do the following:

``` bash
pushd vendor/allegro/protobuf
phpize
./configure --prefix=$HOME/opt/php-5.6
make install
popd
```

`protobuf.so` installed to`$HOME/opt/php-5.6/lib/php/extensions/no-debug-non-zts-20131226`

There is no `php.ini` created by `make install`, so do the following:

``` bash
cp ~/tmp/php-5.6.21/php.ini-development ~/opt/php-5.6/lib/php.ini
```

Edit `php.ini` to include the following lines:

``` ini
extension_dir = "/home/lbakken/opt/php-5.6/lib/php/extensions/no-debug-non-zts-20131226"
extension=protobuf.so
```

**Comment by lukebakken** [comment]
After doing the install rigmarole, tests pass:

``` bash
./vendor/bin/phpunit TimeSeriesOperationsTest vendor/basho/riak/tests/functional/TimeSeriesOperationsTest.php
PHPUnit 4.5.1 by Sebastian Bergmann and contributors.

Configuration read from /home/lbakken/Projects/basho/riak-phppb-client/phpunit.xml

..........

Time: 2.4 seconds, Memory: 4.50MB
```

**Pull request merged**
